#!/bin/sh
# https://github.com/shyiko/ktlint pre-commit hook
echo "start pre-commit"

PROJ_DIR=$(git rev-parse --show-toplevel)

######## KTLINT-GRADLE HOOK START ########
CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"

if [ -z "$CHANGED_FILES" ]; then
    echo "No Kotlin staged files."
    exit 0
fi;

echo "Running ktlint over these files:"
echo "$CHANGED_FILES"

${PROJ_DIR}/gradlew --quiet ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES"

# exit if fail
if [ $? -eq 0 ]; then
    echo "ktlintFormat passed\n"
else
    echo "ktlintFormat failed\n"
    exit 1
fi

${PROJ_DIR}/gradlew --quiet ktlintCheck -PinternalKtlintGitFilter="$CHANGED_FILES"

# exit if fail
if [ $? -eq 0 ]; then
    echo "ktlintCheck passed\n"
else
    echo "ktlintCheck failed\n"
    exit 1
fi

echo "Completed ktlint run."

echo "$CHANGED_FILES" | while read -r file; do
    if [ -f $file ]; then
        git add $file
    fi
done

echo "Completed ktlint hook."
######## KTLINT-GRADLE HOOK END ########
